blank_issues_enabled: false
contact_links:
    - name: Question, feature request and bug report
      - name: Question, feature request and bug report
        url: https://github.com/dscdut/vuejs-boilerplate/issues/new
        about: Request new feature, report bugs and ask questions about the Vue.js boilerplate.
    - name: Discussions
      url: https://discord.com/channels/1249060508644937829/1259132271735078922
      about: Discord channel for discussions about the Vue.js boilerplate.